name: Swift Publish Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Swift
        uses: apple/setup-swift@latest
        with:
          swift-version: '5.5' # Swift 버전에 맞게 설정
      
      - name: Spm Install 
        run: swift package manager tools-update 

      - name: Publish Deploy
        run: |
          publish deploy

