name: Swift Publish Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Swift
        uses: actions/setup-swift@v2
        with:
          swift-version: '5.5' # Swift 버전에 맞게 설정

      - name: Install Dependencies
        run: swift package resolve

      - name: Build and Deploy
        run: |
          swift build -c release
          publish deploy

